import Foundation
final class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    let listings: [Listing] = [
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Ms. Lê Thu Thuỷ",
            ownerImangUrl: "samson1",
            pricePerNight: [
                "Phòng Thường": 700000,
                "Phòng VIP/Executive": 1400000,
                "Phòng Sang trọng": 2800000,
            ],
            latitude: 37.7749,
            longitude: -122.4194,
            address: "Sam Son",
            city: "Thanh Hoa",
            title: "Hercury Hotel",
            rating: 4.8,
            district: "CA",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast,.airConditioning,.wifi,.pool,.parking],
            type: .villa,
            imageUrls: ["samson1","samson2","samson3","samson4"],
            distance: 200
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Ms. Diệu Hương",
            ownerImangUrl: "dalat1",
            pricePerNight: [
                "Phòng Thường": 900000,
                "Phòng VIP/Executive": 1500000,
                "Phòng Sang trọng": 2500000,
            ],
            latitude: 37.7749,
            longitude: -122.4194,
            address: "Da Lat",
            city: "Lam Dong",
            title: "New Century",
            rating: 4.8,
            district: "CA",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast,.airConditioning,.wifi,.pool,.parking],
            type: .villa,
            imageUrls: ["dalat1","dalat2","dalat3","dalat4"],
            distance: 1408
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mr. Ai Do",
            ownerImangUrl: "phuquoc1",
            pricePerNight: [
                "Phòng Chủ tịch": 25000000,
                "Phòng Sang trọng": 6000000,
                "Phòng VIP": 3800000,
                "Phòng thường": 2000000
            ],
            latitude: 37.7749,
            longitude: -122.4194,
            address: "Phu Quoc",
            city: "Kien Giang",
            title: "Seashells Phu Quoc Hotel & Spa",
            rating: 4.8,
            district: "CA",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast,.airConditioning,.wifi,.pool,.parking],
            type: .villa,
            imageUrls: ["phuquoc1","phuquoc2","phuquoc3","phuquoc4"],
            distance: 2017
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mr. Đình Huy",
            ownerImangUrl: "male-profile-photo",
            pricePerNight: [
                "Phòng sang trọng": 3200000,
                "Phòng VIP": 1800000,
                "Phòng thường": 800000
            ],
            latitude: 37.7749,
            longitude: -122.4194,
            address: "Nha Trang",
            city: "Khanh Hoa",
            title: "Liberty Central Nha Trang",
            rating: 4.8,
            district: "CA",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast,.airConditioning,.wifi,.pool,.parking],
            type: .villa,
            imageUrls: ["nhatrang1","nhatrang2","nhatrang3","nhatrang4"],
            distance:  1280
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mr. Sashimi Hihihi",
            ownerImangUrl: "male-profile-photo",
            pricePerNight: [
                "Phòng Chủ tịch": 15000000,
                "Phòng sang trọng": 5000000,
                "Phòng VIP": 3500000,
                "Phòng thường": 2300000
            ],
            latitude: 37.7749,
            longitude: -122.4194,
            address: "Da Nang",
            city: "Da Nang",
            title: "HAIAN Beach Hotel & Spa",
            rating: 4.8,
            district: "CA",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast,.airConditioning,.wifi,.pool,.parking],
            type: .villa,
            imageUrls: ["DaNang1","DaNang2","DaNang3","DaNang4"],
            distance:  741
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mr. Sashimi Hihihi",
            ownerImangUrl: "female-profile-photo",
            pricePerNight: [
                "Phòng sang trọng": 11000000,
                "Phòng VIP": 6500000,
                "Phòng thường": 4400000
            ],
            latitude: 37.7749,
            longitude: -122.4194,
            address: "Saigon",
            city: "Saigon",
            title: "Caravelle Saigon",
            rating: 4.8,
            district: "CA",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast,.airConditioning,.wifi,.pool,.parking],
            type: .villa,
            imageUrls: ["Saigon1","Saigon2","Saigon3","Saigon4"],
            distance:  1600
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Ms. Nguyễn Thị Lan",
            ownerImangUrl: "hanoi1",
            pricePerNight: [
                "Phòng Thường": 1200000,
                "Phòng VIP/Executive": 2500000,
                "Phòng Sang trọng": 4500000,
            ],
            latitude: 21.0245,
            longitude: 105.8412,
            address: "Ha Noi",
            city: "Ha Noi",
            title: "Sofitel Legend Metropole Hanoi",
            rating: 4.9,
            district: "Ba Dinh",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast, .airConditioning, .wifi, .pool, .parking],
            type: .villa,
            imageUrls: ["hanoi1", "hanoi2", "hanoi3", "hanoi4"],
            distance: 20
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mr. Trần Văn Minh",
            ownerImangUrl: "hoian1",
            pricePerNight: [
                "Phòng Thường": 1500000,
                "Phòng VIP": 3200000,
                "Phòng Sang trọng": 6800000,
            ],
            latitude: 15.8801,
            longitude: 108.3380,
            address: "Cam An",
            city: "Hoi An",
            title: "Four Seasons Resort The Nam Hai",
            rating: 4.9,
            district: "Cam An",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast, .airConditioning, .wifi, .pool, .parking],
            type: .villa,
            imageUrls: ["hoian1", "hoian2", "hoian3", "hoian4"],
            distance: 860
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Ms. Phạm Thị Hoa",
            ownerImangUrl: "vungtau1",
            pricePerNight: [
                "Phòng Thường": 850000,
                "Phòng VIP": 1600000,
                "Phòng Sang trọng": 3200000,
            ],
            latitude: 10.4113,
            longitude: 107.1362,
            address: "Ward 1",
            city: "Vung Tau",
            title: "Imperial Hotel Vung Tau",
            rating: 4.6,
            district: "Ward 1",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast, .airConditioning, .wifi, .pool, .parking],
            type: .villa,
            imageUrls: ["vungtau1", "vungtau2", "vungtau3", "vungtau4"],
            distance: 1750
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mr. Lê Văn Hùng",
            ownerImangUrl: "hue1",
            pricePerNight: [
                "Phòng Thường": 900000,
                "Phòng VIP": 1800000,
                "Phòng Hoàng gia": 4200000,
            ],
            latitude: 16.4637,
            longitude: 107.5909,
            address: "Phu Hoi",
            city: "Hue",
            title: "La Residence Hotel & Spa",
            rating: 4.8,
            district: "Phu Hoi",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast, .airConditioning, .wifi, .pool, .parking],
            type: .villa,
            imageUrls: ["hue1", "hue2", "hue3", "hue4"],
            distance: 1020
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mr. Ngô Văn Thành",
            ownerImangUrl: "cantho1",
            pricePerNight: [
                "Phòng Thường": 750000,
                "Phòng VIP": 1400000,
                "Phòng Sang trọng": 2800000,
            ],
            latitude: 10.0341,
            longitude: 105.7880,
            address: "Ninh Kieu",
            city: "Can Tho",
            title: "Vinpearl Hotel Can Tho",
            rating: 4.6,
            district: "Ninh Kieu",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast, .airConditioning, .wifi, .pool, .parking],
            type: .villa,
            imageUrls: ["cantho1", "cantho2", "cantho3", "cantho4"],
            distance: 2150
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Ms. Trương Thị Bích",
            ownerImangUrl: "muine1",
            pricePerNight: [
                "Phòng Thường": 1000000,
                "Phòng VIP": 2100000,
                "Phòng Biển": 4000000,
            ],
            latitude: 10.9332,
            longitude: 108.2880,
            address: "Ham Tien",
            city: "Phan Thiet",
            title: "Anantara Mui Ne Resort",
            rating: 4.7,
            district: "Ham Tien",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast, .airConditioning, .wifi, .pool, .parking],
            type: .villa,
            imageUrls: ["muine1", "muine2", "muine3", "muine4"],
            distance: 1480
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mr. Đinh Quang Khải",
            ownerImangUrl: "quynhon1",
            pricePerNight: [
                "Phòng Thường": 1300000,
                "Phòng VIP": 2800000,
                "Phòng Hướng biển": 5500000,
            ],
            latitude: 13.7650,
            longitude: 109.2118,
            address: "Quy Nhon",
            city: "Binh Dinh",
            title: "AVANI Quy Nhon Resort",
            rating: 4.8,
            district: "Ghenh Rang",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast, .airConditioning, .wifi, .pool, .parking],
            type: .villa,
            imageUrls: ["quynhon1", "quynhon2", "quynhon3", "quynhon4"],
            distance: 1100
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Ms. Vũ Thị Nga",
            ownerImangUrl: "sapa1",
            pricePerNight: [
                "Phòng Thường": 1600000,
                "Phòng VIP": 3500000,
                "Phòng Suite Núi": 7000000,
            ],
            latitude: 22.3364,
            longitude: 103.8438,
            address: "Sa Pa",
            city: "Lao Cai",
            title: "Topas Ecolodge Sa Pa",
            rating: 4.8,
            district: "Sa Pa",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast, .airConditioning, .wifi, .pool, .parking],
            type: .villa,
            imageUrls: ["sapa1", "sapa2", "sapa3", "sapa4"],
            distance: 2150
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mr. Hoàng Anh Tuấn",
            ownerImangUrl: "condao1",
            pricePerNight: [
                "Phòng Thường": 3500000,
                "Phòng VIP": 7000000,
                "Phòng Pool Villa": 15000000,
            ],
            latitude: 8.6800,
            longitude: 106.6060,
            address: "Con Dao",
            city: "Ba Ria - Vung Tau",
            title: "Six Senses Con Dao",
            rating: 4.9,
            district: "Con Dao",
            features: [.superHost, .selfCheckIn],
            amenities: [.breakfast, .airConditioning, .wifi, .pool, .parking],
            type: .villa,
            imageUrls: ["condao1", "condao2", "condao3", "condao4"],
            distance: 1820
        )
    ]
}
